### ISSUE TITLE
React Hook useEffect has missing dependencies: 'getPosts' and 'userId'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

### ISSUE THREAD

**Issue by yosuke1985** [toricls/aws-amplify-sns-workshop-in-vscode#1]
https://amplify-sns.workshop.aws/30_mock/30_post_front_end.html
にて
`./src/containers/PostsBySpecifiedUser.js`

```
 Line 65:6:  React Hook useEffect has missing dependencies: 'getPosts' and 'userId'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
```

とエラーが表示されますが、どのように解決すればよいでしょうか？

**Comment by jaga810** [comment]
`./src/containers/PostsBySpecifiedUser.js` のファイルの中身は以下のリンク先と一致していますでしょうか？
https://amplify-sns.workshop.aws/30_mock/30_post_front_end/_index.ja.files/PostsBySpecifiedUser.js

**Comment by yosuke1985** [comment]
すいません、できました。ありがとうございます！！

**Comment by toricls** [comment]
Thanks @jaga810 for the help 😍

**Comment by jaga810** [comment]
I'm happy for you!
