### ISSUE TITLE
npx create-react-app takes too much time.

### ISSUE THREAD

**Issue by jaga810** [toricls/aws-amplify-sns-workshop-in-vscode#2]
In this workshop I have to run `npx create-react-app` command as below.
https://amplify-sns.workshop.aws/en/30_mock/00_bootstrap.html

```
$ npx create-react-app boyaki
```

It takes too much time to bear!!!

**Comment by toricls** [comment]
@jaga810 
⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛
⬛🍺🍺🍺🍺🍺⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛
⬛🍺⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛🍺⬛⬛⬛⬛⬛⬛⬛🍺⬛⬛⬛⬛
⬛🍺⬛⬛🍺🍺⬛🍺🍺🍺⬛🍺🍺🍺⬛⬛⬛🍺⬛🍺🍺🍺⬛⬛⬛
⬛🍺⬛⬛⬛🍺⬛🍺⬛🍺⬛⬛🍺⬛⬛⬛⬛🍺⬛⬛🍺⬛⬛⬛⬛
⬛🍺🍺🍺🍺🍺⬛🍺🍺🍺⬛⬛🍺🍺⬛⬛⬛🍺⬛⬛🍺🍺⬛🍺⬛
⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛
